version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-sam-datadog-extension-sample"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jplfp9dbcgyl"
s3_prefix = "aws-sam-datadog-extension-sample"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
